TMApp/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact

        public ActionResult ContactView()
        {
            TMAppContext db = new TMAppContext();
            db.ContactsTable.ToList();
           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Message(Contact GetContact)
        {
            TMAppContext db = new TMAppContext();
            var Cont = new Contact();
            Cont.Name = GetContact.Name;
            Cont.Email = GetContact.Email;
            Cont.Subject = GetContact.Subject;
            Cont.Message = GetContact.Message;

           
            db.ContactsTable.Add(Cont);
           
            db.SaveChanges();

            TempData["msg"] = "<script> alert('Message Sent');</script>";
            return RedirectToAction("ContactView");
        }
       
    }
}

TMApp/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class ProfileController : Controller
    {

        [HttpGet]
        public ActionResult MyProfile()
        {

            TMAppContext db = new TMAppContext();
            var Users = db.RegistersTable.Find(Session["Email"]);
         
        
            return View(Users);

        }

        

      


        public ActionResult PasswordView()
        {


            return View();
        }
        public ActionResult EditPwd()
        {
            return View();
        }

    }

}

TMApp/Controllers/ScheduleSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class ScheduleSetController : Controller
    {


        public ActionResult ScheduleSetView()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ScheduleSet(ScheduleSet Task)
        {
            if (ModelState.IsValid)
            {


                TMAppContext db = new TMAppContext();
                ScheduleSet newTask = new ScheduleSet();
                newTask.Description = Task.Description;
                newTask.Categories = Task.Categories;
                newTask.Date = Task.Date;
                newTask.Location = Task.Location;
                newTask.Email = Task.Email;
                //newTask.Username = Task.Username;
                //newTask.Password = Task.Password;
                Task.Status = "Active";

                var CheckUser = db.RegistersTable.Where(m => m.Email.Equals(Task.Email));
                // var CheckUser = db.RegistersTable.Where(m => m.Username.Equals(Task.Username) && m.Password.Equals(Task.Password)).FirstOrDefault();
                if (CheckUser != null)
                {
                    db.ScheduleSetsTable.Add(newTask);
                    db.SaveChanges();

                    TempData["Msg"] = "<script> alert('Task Successfully set');</script>";
                    return RedirectToAction("ScheduleSetView");

                }
                else
                {
                    TempData["Errormsg"] = "<script> alert('Email not registered');</script>";
                    return View("ScheduleSetView");
                }


            }
            return View("ScheduleSetView");
        }
        
    }
}

TMApp/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/img/favicon.png" type="image/png">
    <title>Task Manager</title>


    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/animate-css/animate.css">



    <link href="~/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/responsive.css">

    <script src="~/js/MyScript.js"></script>
</head>
<body>

    <header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg " style="background-color:mediumslateblue">
                <div class="container">

                    @*<a class="navbar-brand logo_h" href="index.html"><img src="~/img/logo.png" alt=""></a>*@
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item">@Html.ActionLink("Home", "Home", "Home", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("About Us", "AboutView", "Home", null, new { @class = "nav-link" })
                            <li class="nav-item">@Html.ActionLink("Contact Us", "ContactView", "Contact", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("EmailView","EmailView","Email",null,new { @class="nav-link"})</li>
                        </ul>
                    </div>
                    <div class="right-button">
                        <ul>
                            <li class="genric-btn danger medium">@Html.ActionLink("Login", "LoginView", "Login")</li>

                            <li class="genric-btn danger medium">@Html.ActionLink("Register", "RegisterView", "Register")</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>


    @RenderBody();

    @*@RenderSection("scripts", required: false)*@


    <footer class="footer-area">
        <div class="container">

            <div class="footer-bottom row align-items-center text-center text-lg-left no-gutters">
                <p class="footer-text m-0 col-lg-8 col-md-12">
                    Copyright ©
                    <script type="5b4f23bc0a6c1f9f4e183589-text/javascript">document.write(new Date().getFullYear());</script> Damilola Okunlola. All rights reserved.
                </p>
                <div class="col-lg-4 col-md-12 text-center text-lg-right footer-social">
                    <a href="#"><i class="ti-facebook"></i></a>
                    <a href="#"><i class="ti-twitter-alt"></i></a>
                    <a href="#"><i class="ti-dribbble"></i></a>
                    <a href="#"><i class="ti-linkedin"></i></a>
                </div>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/js/jquery-2.2.4.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/popper.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/bootstrap.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.ajaxchimp.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/waypoints.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/contact.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.form.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.validate.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/theme.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>


    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js"
            data-cf-settings="ab3c4cb7254640bc182b1ba0-|49" defer=""></script>

  
</body>

</html>

TMApp/Views/Shared/_UserLayout.cshtml
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/img/favicon.png" type="image/png">
    <title>Task Manager</title>

    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/animate-css/animate.css">
          
   

    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">

   

</head>
<body>

    <header class="header_area">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg" style="background-color:mediumslateblue">
                <div class="container">

                    @*<a class="navbar-brand logo_h" href="index.html"><img src="~/img/logo.png" alt=""></a>*@
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            @*<li class="nav-item">@Html.ActionLink("Home", "Home", "Home", null, new { @class = "nav-link" })</li>*@
                            <li class="nav-item">@Html.ActionLink("UserPage", "UserPage", "UserPage", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Set Task", "ScheduleSetView", "ScheduleSet", null, new { @class = "nav-link" })
                            <li class="nav-item">@Html.ActionLink("TaskList", "TaskList", "TaskList", null, new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("My Profile", "MyProfile", "Profile", null, new { @class = "nav-link" })</li>
                         

                        </ul>
                    </div>
                    <div class="right-button">
                        <ul>


                            <li class="genric-btn" style="color:#ffffff">@Session["Email"].ToString()</li>
                            <li class="genric-btn danger">@Html.ActionLink("Logout", "Logout", "UserPage")</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>


    @RenderBody();

    @RenderSection("scripts", required: false)


    <footer class="footer-area">
        <div class="container">

            <div class="footer-bottom row align-items-center text-center text-lg-left no-gutters">
                <p class="footer-text m-0 col-lg-8 col-md-12">
                    Copyright ©
                    <script type="5b4f23bc0a6c1f9f4e183589-text/javascript">document.write(new Date().getFullYear());</script> Damilola Okunlola. All rights reserved.
                </p>
                <div class="col-lg-4 col-md-12 text-center text-lg-right footer-social">
                    <a href="#"><i class="ti-facebook"></i></a>
                    <a href="#"><i class="ti-twitter-alt"></i></a>
                    <a href="#"><i class="ti-dribbble"></i></a>
                    <a href="#"><i class="ti-linkedin"></i></a>
                </div>
            </div>
        </div>

    </footer>
    @*<script src="~/Scripts/jquery-3.5.1.min.js"></script>
        <script src="~/Scripts/popper.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>*@


    <script src="~/js/jquery-2.2.4.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>


    <script src="~/js/popper.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>

    <script src="~/js/bootstrap.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.ajaxchimp.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/waypoints.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/contact.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.form.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.validate.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/theme.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>


    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js"
            data-cf-settings="ab3c4cb7254640bc182b1ba0-|49" defer=""></script>

    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


</body>

</html>