TMApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class LoginController : Controller
    {
        
       
        
        public ActionResult LoginView()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Authorize(Register reg) 
        {
            

   


                using (TMAppContext db = new TMAppContext())
                {
                    var UserDetails = db.RegistersTable.Where(model => model.Username == (reg.Username) && model.Password == (reg.Password)).FirstOrDefault();
                    if (UserDetails != null)
                    {

                    reg.LastLogin = DateTime.Now;

                        //Login.Username = reg.Username;
                        //Login.Password = reg.Password;
                        //Login.LoginDate = DateTime.Now;

                        //db.UserLoginsTable.Add(Login);
                        db.SaveChanges();


                        Session["Username"] = UserDetails.Username;
                        Session["Email"] = UserDetails.Email;
                        return RedirectToAction("UserPage", "UserPage");
                    }

                    else
                    {
                        TempData["Errormsg"] = "<script> alert('Wrong Username or Password');</script>";
                        return View("LoginView");


                    }

                
                }
          
             
        }

                
            
          
           
        
    }
}

TMApp/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class RegisterController : Controller
    {

        
        public ActionResult RegisterView()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Register model)
        {
            if (ModelState.IsValid)
            {


                try
                {
                    TMAppContext db = new TMAppContext();
                    Register reg = new Register();
                    //db.Database.ExecuteSqlCommand("SET IDENTITY_INSERT dbo.tblRegister ON");
                    reg.Name = model.Name;
                    reg.Email = model.Email;
                    reg.Gender = model.Gender;
                    reg.Country = model.Country;
                    reg.State = model.State;
                    reg.PhoneNo = model.PhoneNo;

                    reg.Username = model.Username;
                    reg.Password = model.Password;
                    reg.DateRegistered = DateTime.Today;
                    reg.LastLogin = DateTime.Now;
                    reg.LastUpdate = DateTime.Now;
                    if (model.Gender == "Female")
                    {
                        reg.ProfilePic = "~/images/profile Pictures/female avarta2.png";
                    }
                    else
                    {
                        reg.ProfilePic = "~/images/profile Pictures/male avarta.jpg";
                    }

                    if (ModelState.IsValid)
                    {
                        var CheckEmail = db.RegistersTable.Find(model.Email);
                        var CheckUsername = db.RegistersTable.Find(model.Username);

                        if (CheckEmail != null)
                        {
                            TempData["Error"] = "<script> alert('Email already Exist'); </script>";
                        }
                        else if (CheckUsername != null)
                        {
                            TempData["UsernameError"] = "<script> alert('Username already Exist'); </script>";
                        }
                        else
                        {
                            db.RegistersTable.Add(reg);
                            db.SaveChanges();
                            //db.Database.ExecuteSqlCommand("SET IDENTITY_INSERT dbo.tblRegister OFF");
                            TempData["msg"] = "<script> alert('Succesfully Registered!! Login to access more features');</script>";

                            return RedirectToAction("LoginView", "Login");
                            //TempData["Error"] = "<script> alert('Invalid Entry'); </script>";



                        }


                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }


            return View("RegisterView");
        }

       public ActionResult Clear()
        {

            return View();
        }

    }
}

TMApp/Views/Login/LoginView.cshtml
@model TMApp.Models.Register
@{
    Layout = null;
}


<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/img/favicon.png" type="image/png">
    <title>Task Manager</title>

    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="~/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/vendors/animate-css/animate.css">

    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <link rel="stylesheet" href="~/css/main.css">
   
</head>

<body style="background:url(../img/background/._dot-pattern.jpg) repeat;">


    <div data-overlay class="min-vh-100 d-flex flex-column justify-content-md-center" style="padding-top: 80px !important;">
        <section class="py-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-4 col-lg-5 col-md-6">
                        <div class="card card-body shadow">
                            <h1 class="h5 text-center" style="margin-bottom: 1rem;">Sign In</h1>
                            @using (Html.BeginForm("Authorize", "Login", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken();
                                <div class="form-control-file" id="login" style="padding-left:20px;padding-right:20px">


                                    <div class="form-group row" style="color:black">

                                        <div class="col-sm-10">
                                            @Html.TextBoxFor(model => model.Username, new { @class = "form-control", @placeholder = "Username", @type = "text", id = "txtUsername" })
                                        </div>
                                        <p style="color:red"> @Html.ValidationMessageFor(model => model.Username)</p>
                                    </div>
                                    <br />


                                    <div class="form-group row" style="color:black">

                                        <div class="col-sm-10">
                                            @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @placeholder = "...........", @type = "password", id = "txtPwd" })
                                        </div>
                                        <p style="color:red"> @Html.ValidationMessageFor(model => model.Password)</p>
                                    </div>
                                    
                                    <br />
                                    <div class="form-group">

                                        <button @("Authorize") class="btn btn-primary btn-block" type="submit" id="SignUp" style="background-color: #db4c3f; border-color: #db4c3f;">Sign In</button>
                                        <div class="text-center text-small mt-3" style="color: #db4c3f;">
                                            Don't have an account? @Html.ActionLink("Sign Up here","RegisterView","Register")
                                        </div>

                                        @Html.Raw(TempData["Errormsg"])
                                    </div>

                                </div>
                            }


                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="background">
        <div class="leftLarge">

        </div>
        <div class="rightLarge">
        </div>
    </div>





    <script src="~/js/jquery-2.2.4.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/popper.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/bootstrap.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/vendors/owl-carousel/owl.carousel.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.ajaxchimp.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/waypoints.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/contact.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.form.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/jquery.validate.min.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/mail-script.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>
    <script src="~/js/theme.js" type="ab3c4cb7254640bc182b1ba0-text/javascript"></script>


    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" 
            data-cf-settings="ab3c4cb7254640bc182b1ba0-|49" defer=""></script>
</body>

</html>