TMApp/Controllers/ChangePwdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMApp.Models;

namespace TMApp.Controllers
{
    public class ChangePwdController : Controller
    {
        // GET: ChangePwd
        public ActionResult ChangePwdView()
        {
            return View();
        }

        //    public ActionResult ChangePwd( string New, Register User)
        //    {

        //        string NewPwd = Convert.ToString(Request["txtPwd"].ToString());
        //        string Email = (string)Session["Email"];
        //        TMAppContext db = new TMAppContext();
        //        var VerifyUser = db.RegistersTable.Where(m => m.Password.Equals(User.Password) && m.Email.Equals(Email)).FirstOrDefault();
        //        if (VerifyUser != null)
        //        {
        //            VerifyUser.Password = NewPwd; ;
        //            db.SaveChanges();
        //            TempData["msg"] = "<script>alert('Passowrd Reset');</script>";
        //        }
        //        else
        //        {

        //            TempData["Error"] = "<script>alert('Incorrect Password');</script>";
        //        }

        //        return View();
        //    }


        //}
    }
}

TMApp/Views/ChangePwd/ChangePwdView.cshtml
@model TMApp.Models.Register
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChangePwd</title>
</head>
<body>

    <div data-overlay class="min-vh-100 d-flex flex-column justify-content-md-center" style="padding-top: 80px;">
        <section class="py-3">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-4 col-lg-5 col-md-6">
                        <div class="card card-body shadow">
                            <h1 class="h5 text-center" style="margin-bottom: 1rem;">Reset Password</h1>
                            @using (Html.BeginForm("ChangePwdView", "ChangePwd", FormMethod.Post))
                            {
                                Html.AntiForgeryToken();

                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @placeholder = "Old Password", id = "txtPassword", @type = "password", @required = "required" })

                                    <p style="color:red"> @Html.ValidationMessageFor(model => model.Password)</p>

                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control" name="txtPwd" id="txtPwd" placeholder="New Password" required>

                                    <small>Password must be at least 5 characters</small>
                                    <p style="color:red"> @Html.ValidationMessageFor(model => model.Password)</p>

                                </div>


                                <button @("ChangePwd") class="btn btn-primary btn-block" type="submit" style="background-color: #db4c3f; border-color: #db4c3f;">Reset My Password</button>
                                @Html.Raw(TempData["msg"])
                                @Html.Raw(TempData["Error"])
                            }
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="background">
        <div class="leftLarge">
        </div>
        <div class="rightLarge">
        </div>
    </div>



</body>
</html>